### ISSUE TITLE
multiple hosts

### ISSUE THREAD

**Issue by joshp23** [pztop/namesilo_ddns#3]
does this script work with multiple hosts under a single domain? or does it need a separate instance for each host and domain?

**Comment by dynaguy1** [comment]
This script only update ONE host under single domain.  If you want it to handle multiple hosts and/or multiple domains, you may fork it and modify the script. 

You may also give the script different names and run multiple cronjob accordingly.

**Comment by pztop** [comment]
This script only update ONE host under single domain. If you want it to handle multiple hosts and/or multiple domains, you may fork it and modify the script.

You may also give the script different names and run multiple cronjob accordingly.

**Comment by pztop** [comment]
Closed.
