### ISSUE TITLE
script needs update?

### ISSUE THREAD

**Issue by fozters** [pztop/namesilo_ddns#8]
In the readme there is stated:
##Host name (subdomain). Optional. If present, must end with a dot (.)
HOST="test."

Which leads to two dots on subdomain:
cat /tmp/namesilo_response.xml
<?xml version="1.0"?>
<namesilo><request><operation>dnsUpdateRecord</operation><ip>xx.xxx.xx.xxx</ip></                                       request><reply><code>280</code><detail>test**..**abcd.com is not a valid host</d                                       etail></reply></namesilo>

Easy fix is to leave out following dot but after that you get other xpath error:
fozters@printer:/namesilo_ddns$ sudo ./namesilo_ddns.sh
[sudo] password for fozters:
XPath set is empty

cat /tmp/namesilo_response.xml
<?xml version="1.0"?>
<namesilo><request><operation>dnsUpdateRecord</operation><ip>xxx.xx.xx.xxx</ip></request><reply><code>108</code><detail>Missing parameters for the specified operation</detail></reply></namesilo>

any idea for a fix?

**Comment by pztop** [comment]
Sorry I no longer use Namesilo's DNS service so I can't troubleshot the issue you reported here any more.

What I suggested is you can run the script like this:
`bash -x namesilo_ddns.sh` 
You can analyse the output then figure out what went wrong.

**Comment by fozters** [comment]
Hi, 
Noted, will try, thanks for reply.

**Comment by fozters** [comment]
Thanks, it indeed does give more output but seems to result with 108 error code:
XPath set is empty
+ RECORD_ID=
+ curl -s 'https://www.namesilo.com/api/dnsUpdateRecord?version=1&type=xml&key=85dbxxxxxxxxxxxxx&domain=xxxyyyyzzzz.com&rrid=&rrhost=test&rrvalue=xx.xxx.xxx.xx&rrttl=3600'
++ xmllint --xpath '//namesilo/reply/code/text()' /tmp/namesilo_response.xml
+ RESPONSE_CODE=108
+ case $RESPONSE_CODE in
+ echo
+ logger -t IP.Check -- DDNS update failed code '108!'
+ exit 0
fozters@printer:/namesilo_ddns$ cat /tmp/namesilo_response.xml
<?xml version="1.0"?>
<namesilo><request><operation>dnsUpdateRecord</operation><ip>xx.xx.xx.xx</ip></request><reply><code>108</code><detail>Missing parameters for the specified operation</detail></reply></namesilo>

If you have moved on don't worry about fixing this, thanks anyway and merry xmas.

**Comment by welpher** [comment]
add a dot here fix it
RECORD_ID=`xmllint --xpath "//namesilo/reply/resource_record/record_id[../host/text() = '$HOST.$DOMAIN' ]" $DOMAIN.xml

**Comment by sudowanderer** [comment]
I updated a new version. Tested worked fine in Ubuntu20.04.
https://github.com/xiaod-dev/namesilo_ddns

**Comment by fozters** [comment]
As per xiaod-dev comment and as this script is "abandonware" -> closing this issue.
